Version 1.1.0
futuredapp/FuturedKit pull request #26
Opened 2024-08-07 12:09 UTC by ssestak

- Template Updates
   - Removed SwiftLint warnings
   - Omitted application prefix in naming
   - Dropped class prefix in mock view model events
- Added commentary explaining anti-pattern of adding view modifiers in coordinator root view
- Alerts no longer managed by coordinators; their presentation is now individual view's responsibility
- Scene Delegate
   - Introduced view modifier in helpers
- Destination IDs
   - Integrated `@EnumIdentifiersGenerator` macro for auto-generating code for `Hashable` and `Identifiable` protocol conformance
   - The macro produces nested enum for ID generation for enum cases
- Introduced FlowProvider in helpers
- For coordinators, integrated `ModalCoverModel<Destination>` to avoid UI confusion regarding sheet and full screen cover presentation order

Prerequisites for Merging:
- New projects must specify a key-value pair for `LaunchScreen` in `Info.plist` to ensure proper display
- Macro 
   - Requires importing `EnumIdentifiersGenerator` currently, but ideally, it should be part of `FuturedArchitecture`
      -  _UPDATE_: Macro moved into a separate [git repository](https://github.com/futuredapp/futured-macros)
   - It doesn't account for situation when Destination ID needs to be computed using an associated value
      - _UPDATE_: DONE

_Macro Expansion Example:_
<img width="472" alt="image" src="https://github.com/user-attachments/assets/d030ca83-1b90-4d6e-831c-f702fd27d71c">

2024-08-08 09:26 UTC, samoilyk approved these changes, later dismissed

2024-08-15 13:31 UTC, samoilyk approved these changes, later dismissed

2024-08-15 14:30 UTC, mikolasstuchlik requested changes
Overall a great piece of pioneering work!

2024-08-15 14:30 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +protocol CoordinatorSceneFlowDestination: Hashable, Identifiable, Equatable {}
Can be 
```suggestion
typealias CoordinatorSceneFlowDestination = Hashable & Identifiable & Equatable
```

2024-08-15 14:30 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +/** A protocol to represent navigable destinations in a reusable scene flow
Please provide a documentation

2024-08-15 14:30 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +/**
Please provide a shorter documentation. 
In my opinion, code examples should be no more than 10 lines of code in once block.

Having a template would be great, as discussed on the call.

2024-08-15 14:30 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +    var onPopToDestination: ((Destination?) -> Void)? { get }
Please document, what is the significance of `nil` argument.

2024-08-15 14:30 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +        })
This is a matter of opinion, but I prefer following multi-closure function calls:
```suggestion
        TemplateSceneFlowProvider(
            container: container, 
            onNavigateToDestination: { [weak self] destination in
                if destination == .end {
                    self?.navigate(to: .flowSpecificDestinationAfterEmbededFlow)
                } else {
                    self?.navigate(to: destination)
                }
            },
            onPop: { [weak self] in
                self?.pop()
            }
        )
```

2024-08-15 14:30 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +    }
I don't understand the reason for this extension. If the _only_ reason for this extension existence is to have _nicer_ API, I would suggest to rename the closures.

I think that reasoning the code is made _more_ difficult, not less, and thus I would only keep the closures.

For sake of transparency, I have also renamed a variable in similar manner, but in my case, I have introduced different access modifiers to separate contexts and I've only done it for 1 variable.

2024-08-15 14:30 UTC, mikolasstuchlik commented on Templates/SwiftUI App.xctemplate/ExampleFlowCoordinator.swift
>      enum Destination: String, Hashable, Identifiable {
```suggestion
    enum Destination: Hashable, Identifiable {
```

We also might make this macro add the conformances, as previously discussed. 

https://github.com/futuredapp/futured-macros/pull/1

2024-08-15 14:30 UTC, mikolasstuchlik commented on Templates/Tab Coordinator.xctemplate/___VARIABLE_tabCoordinatorIdentifier___TabCoordinator.swift
> +    }
```suggestion
    @EnumIdentable
    enum Destination: Hashable, Identifiable {
        case destination
    }
```

2024-08-15 14:33 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +    }
On second thought, I almost lean to a conclusion, that `protocol` is just a bad tool for this job. I would almost suggest to use `class` inheritance.

2024-08-16 11:40 UTC, samoilyk submitted a review, later dismissed

2024-08-16 12:07 UTC, mikolasstuchlik requested changes

2024-08-16 12:07 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> + # Example #
```suggestion
 # Example #
  Declare a `protocol` conforming to the composition. The protocol should only be conformed to by enums. We use the requirements to force appearance of certain cases: [SE-0280](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0280-enum-cases-as-protocol-witnesses.md).
```

2024-08-16 12:07 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> +    static var end: Self { get }
We probably should use naming which does not appear to have a special meaning, if it is only an example.

```suggestion
    static var someDestination: Self { get }
    static var otherDestionation: Self { get }
```

2024-08-16 12:07 UTC, mikolasstuchlik commented on Sources/FuturedHelpers/Helpers/CoordinatorSceneFlowProvider.swift
> + A protocol providing an interface for reusable scene flow providers.
What is a _reusable scene flow provider_? Is my suggestion correct?

```suggestion
 A protocol providing an interface for reusable scene flow providers. *Reusable scene flow provider* is part of a scene flow, which can be used as a part of more *Flow Coordinators*. The shared section of the flow is taken out of the *Flow Coordinator* and placed into a class conforming to `CoordinatorSceneFlowProvider`. 
```

2024-08-16 12:07 UTC, mikolasstuchlik commented on Templates/Flow Coordinator.xctemplate/___VARIABLE_flowCoordinatorIdentifier___FlowCoordinator.swift
> +    enum Destination: Hashable, Identifiable {
I still think we should make the `@EnumIdentable` add the conformance. I don't think it's MUST-HAVE at this point, but please, file an Issue to this effect.

2024-08-16 12:07 UTC, mikolasstuchlik commented on Templates/SceneFlowProvider.xctemplate/___VARIABLE_sceneFlowProviderIdentifier___SceneFlowProvider.swift
> +
```suggestion

```

2024-08-16 12:07 UTC, mikolasstuchlik commented on Templates/SceneFlowProvider.xctemplate/___VARIABLE_sceneFlowProviderIdentifier___SceneFlowProvider.swift
> +}
I don't see why we need to do this. The `Destination` should be only a generic parameter of the `___VARIABLE_sceneFlowProviderIdentifier___SceneFlowProvider` and conformed to by the Destinations of the _Flow cooridnators_.

If I am not correct, why do we need `___VARIABLE_sceneFlowProviderIdentifier___FlowDestination` at all?

2024-08-16 12:10 UTC, mikolasstuchlik commented
It is still not fully clear to me, how the Scene Provider should work. I don't want to hinder the acceptance because of the documentation. I have made some requests and the rest of it can be deferred to an Issue (on both FuturedKit and macros).

However, I'm reluctant to merge Scene Provider in this state.

2024-08-16 13:41 UTC, mikolasstuchlik approved these changes

2024-08-16 13:42 UTC, mikolasstuchlik commented
![86580cded392542b51fe48041237db67](https://github.com/user-attachments/assets/f54db3dc-5fb2-4e08-b33f-815c019d9364)

2024-08-16 15:11 UTC, merged